name: compliance

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    paths:
      - "latest/**"
    

jobs:
  check-compliance-labels:
    if: contains(github.event.pull_request.labels.*.name, 'backend')
    runs-on: ubuntu-latest
    steps:
      - run: |
          labels='${{ toJson(github.event.pull_request.labels.*.name) }}'
          echo "PR labels: ${labels}"

          if ! echo "$labels" | grep -q '"Standard Change"'; then
            echo "::error::Missing required Stanard Change label on the PR
            exit 1
          fi
