on:
  pull_request_target:
    types: 
      - closed
    branches:
      - main

jobs:
  # release-public-unstable:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
      

  release-public:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: echo meep
